global:
  pullSecret:
  registry:
    url: armdocker.rnd.ericsson.se
  ingress:
    enmHost:
    class: ingress-nginx
  timezone:
  enmProperties:
    COM_INF_LDAP_ADMIN_ACCESS:
    COM_INF_LDAP_PORT:
    COM_INF_LDAP_ROOT_SUFFIX:
    COM_INF_LDAP_ADMIN_CN:
    postgres_service: postgres
    postgresql01_admin_password:
    default_security_admin_password:
    LDAP_ADMIN_CN:
    LDAP_ADMIN_PASSWORD:
productNumber: "CXC 174 1909"
productRevision: RSTATE
labels: {}
securityPolicy:
  rolename: cenmproxy
replicas-eric-oss-enm-aa-proxy: 1
images:
  eric-oss-enm-aa-proxy:
    name: eric-oss-enm-aa-proxy
    tag: VERSION
  eric-enm-httpd:
    name: eric-oss-enm-aa-proxy-httpd
    tag: VERSION
  eric-enm-monitoring:
    enabled: true
    name: eric-enm-monitoring-eap7
    tag: 1.64.0-33
  waitForCertificatesContainer:
    enabled: true
    name: enm-wait-for-certificates-container
    tag: 1.52.0-33
imageCredentials:
  repoPath: proj-enm
  pullPolicy: IfNotPresent
  pullSecret:
  registry:
    url:
eric-enm-common-helmchart-library:
  enabled: true
service:
  name: cenmproxy
  sgname: cenmproxy
  annotations: {}
  labels:
  xmlMountPath: "/ericsson/credm/certReqMount"
  tlsMountPath: "/ericsson/credm/tlsMount"
ingress:
  enabled: true
ingress_jboss_web_context:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
resources:
  requests:
    enabled: true
    memory: 2048Mi
    cpu: 300m
    ephemeral-storage: 1000Mi
  limits:
    enabled: true
    memory: 3072Mi
    cpu: 1
    ephemeral-storage: 3000Mi
  httpd:
    enabled: true
    requests:
      memory: 400Mi
      cpu: 250m
      ephemeral-storage: 500Mi
    limits:
      memory: 1000Mi
      cpu: 500m
      ephemeral-storage: 2000Mi
  monitoring:
    enabled: true
    requests:
      memory: 300Mi
      cpu: 50m
      ephemeral-storage: 250Mi
    limits:
      memory: 400Mi
      cpu: 200m
      ephemeral-storage: 250Mi
startupProbe:
  enabled: true
  command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
  arguments: --exec_agents
  initialDelaySeconds: 10
  timeoutSeconds: 30
  periodSeconds: 30
  failureThreshold: 20
livenessProbe:
  enabled: true
  command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
  arguments: --exec_agents
  initialDelaySeconds: 30
  timeoutSeconds: 30
  periodSeconds: 30
  failureThreshold: 2
readinessProbe:
  enabled: true
  command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
  arguments: --exec_agents
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 30
  failureThreshold: 2
podAnnotations: {}
tolerations: []
affinity: requiredDuringSchedulingIgnoredDuringExecution
nodeAffinity: {}
priorityClassName: ""
nodeSelector: {}
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0
podDisruptionBudget:
  maxUnavailable: 1
securityContext:
  cenmproxy:
    allowPrivilegeEscalation: true
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    capabilities:
      drop:
      - all
      add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - SYS_RESOURCE
      - SYS_NICE
      - SYS_ADMIN
      - SYSLOG
      - NET_ADMIN
      - DAC_READ_SEARCH
      - SYS_PTRACE
  monitoring:
    allowPrivilegeEscalation: true
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    capabilities:
      drop:
      - all
      add:
      - DAC_READ_SEARCH
      - DAC_OVERRIDE
      - FOWNER
      - SYS_ADMIN
      - SYS_RESOURCE
  waitInitContainer:
    allowPrivilegeEscalation: true
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    capabilities:
      drop:
      - all
  httpd:
    allowPrivilegeEscalation: true
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    capabilities:
      drop:
      - all
      add:
      - CHOWN
      - DAC_OVERRIDE
      - DAC_READ_SEARCH
      - FOWNER
      - FSETID
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
      - SYSLOG
      - SYS_ADMIN
      - SYS_RESOURCE
  waitForCertificatesContainer:
    allowPrivilegeEscalation: true
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    capabilities:
      drop:
      - all
credmController:
  name: eric-enm-credm-controller
  port: 5001
jobs:
  jobAction: certrequest
  certRequest:
    imageName: enm-certrequestjob-container
    pullPolicy: IfNotPresent
    tag: 1.52.0-33
    resources:
      requests:
        enabled: true
        cpu: 500m
        memory: 512Mi
      limits:
        enabled: true
        cpu: 1000m
        memory: 512Mi
