- name: data
  mountPath: /ericsson/tor/data
- name: gp
  mountPath: /gp
- name: tls-secret-1
  mountPath: {{ .Values.service.tlsMountPath }}/tls1
- name: tls-secret-2
  mountPath: {{ .Values.service.tlsMountPath }}/tls2


